config/routes.rb
require 'monban/constraints/signed_in'
require 'monban/constraints/signed_out'

Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resources :users

  constraints Monban::Constraints::SignedIn.new do
    get '/', to: 'dashboards#index', as: :dashboard
  end

  constraints Monban::Constraints::SignedOut.new do
    # root 'landings#show'
  end

  root 'sessions#new'
end

app/models/game.rb
class Game < ActiveRecord::Base
  validates :week, presence: true
  validates :home_team, presence: true
  validates :away_team, presence: true
  validates :start_time, presence: true

  belongs_to :week
  belongs_to :home_team, class_name: "Team"
  belongs_to :away_team, class_name: "Team"
  belongs_to :winning_team, class_name: "Team"

  has_many :picks
end

app/models/pick.rb
class Pick < ActiveRecord::Base
  validates :user, presence: true
  validates :game, presence: true

  belongs_to :user
  belongs_to :game
  belongs_to :team
end

app/models/season.rb
class Season < ActiveRecord::Base
  validates :start_date, presence: true, uniqueness: true
end

app/models/team.rb
class Team < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :location, presence: true

  has_many :picks
  has_many :home_teams, class_name: 'Game', foreign_key: 'home_team_id'
  has_many :away_teams, class_name: 'Game', foreign_key: 'away_team_id'

  def location_and_name
    "#{location} #{name}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true, case_sensitive: false
  validates :password_digest, presence: true
  validates :username, presence: true, uniqueness: true, case_sensitive: false

  has_many :picks

  def name
    "#{first_name} #{last_name}"
  end
end

app/models/week.rb
class Week < ActiveRecord::Base
  validates :start_date, presence: true, uniqueness: true

  has_many :games
  belongs_to :season
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers

  protect_from_forgery with: :exception
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    user = authenticate_session(session_params)

    if sign_in(user)
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:email, :password, :username)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  before_action :find_user, only: [:show, :edit, :update, :ensure_user]
  before_action :ensure_user, only: [:edit, :update]

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = sign_up(user_params)

    if @user.valid?
      sign_in(@user)
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :email,
      :password,
      :username,
      :first_name,
      :last_name
    )
  end

  def ensure_user
    return false if current_user == @user
    redirect_to user_path(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_errors.html.erb
<% if target.errors.any? %>
  <%= pluralize(@user.errors.count, "error") %> prevented your account from being created:
  <ul>
    <% target.errors.full_messages.each do |error_message| %>
      <li><%= error_message %></li>
    <% end %>
  </ul>
<% end %>

app/views/application/_flash_msg.html.erb
<% flash.each do |name, message| %>
      <%= content_tag :div, message, class: name %>
<% end %>

app/views/dashboards/index.html.erb
Hello <%= current_user.username %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pickem</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <h1><%= link_to "Pickem", root_path %></h1>
  <% if signed_in? %>
    <div class="user_nav" style="float: right">
      <span><%= link_to current_user.username, user_path(current_user) %></span>
      <span style="float: right"><%= button_to "Sign out", session_path, method: :delete %></span>
    </div>
  <% end %>
  <%= render "flash_msg" %>
  <%= yield %>
</body>
</html>

app/views/users/edit.html.erb
<%= form_for @user do |form| %>
  <% if @user.errors.any? %>
    <%= pluralize(@user.errors.count, "error") %> prevented your account from being saved:
    <ul>
      <% @user.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  <% end %>
  <div>
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.submit "Update" %>
  </div>

  <div>
    <%= button_to "Cancel", user_path(@user) %>
  </div>
<% end %>

app/views/users/new.html.erb
<%= form_for @user do |form| %>
  <%= render "errors", target: @user %>

  <div>
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.submit "Sign up" %>
  </div>

  <div>
    Have an account? <%= link_to "Sign In", [:new, :session] %>
  </div>
<% end %>

app/views/users/show.html.erb
<% if current_user == @user %>
  <%= link_to "Edit Profile", edit_user_path(@user) %>
<% end %>
<div>Username: <%= current_user.username %></div>
<div>First Name: <%= current_user.first_name %></div>
<div>Last Name: <%= current_user.last_name %></div>